hook:
  container_name: mail-in-processing
  environment:
    SQL_HOST: mail-db
    SQL_PORT: 3306
    SQL_USER: root
    SQL_PASSWORD: ElyIg2G9RKkEglizc58A
    SQL_DATABASE: mail
    SQL_TABLE_PLAINTEXT: ingoing
    SQL_TABLE_FILTERED: ingoing-processing
  build: .
  # TODO Use COPY directive in Dockerfile instead
  volumes:
    - ./filter-mails.php:/filter-mails.sh
  external_links:
    - mail-db
  tty: true
  stdin_open: true
  restart: always
