smtpd:
  container_name: mail-out
  ports:
    - "15025:25/tcp"
    - "15587:587/tcp"
  build: .
  dockerfile: Dockerfile-opensmtpd
  volumes:
    - ./smtpd.conf:/etc/smtpd/smtpd.conf:ro
    #- ../DATA/mail-out/spool-smtpd:/var/spool/smtpd
    #- ./DATA-spool-smtpd:/var/spool/mail
  links:
    - dovecot
  tty: true
  stdin_open: true
  restart: always

dovecot:
  container_name: mail-out_dovecot
  ports:
    - "15143:143/tcp"
    - "15993:993/tcp"
  image: instrumentisto/dovecot:alpine
  volumes:
    - ../DATA/mail-out/dovecot:/home/vmail/
    - ./dovecot-local.conf:/etc/dovecot/local.conf
    - ./dovecot-passwd:/etc/dovecot/my-passwd
  tty: true
  stdin_open: true
  restart: always
